### PR TITLE
New application form

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by lachlanjc** [comment]
From this point let’s consider using Rebass deprecated (see #52), and switch this to DS before launch (unless we’ve got a deadline). The main changes are using its ThemeProvider (https://github.com/hackclub/site/pull/52/files#diff-208b86e4eb4080a2cc134786e1d290bb), switching the `import`s, and probably fixing some spacing. I have not used the new form components much so we’ll likely have to update those a bit. I can totally help out with this.

**Comment by maxwofford** [comment]
@lachlanjc: I'll look into the new design system once this PR is done. This is already past it's deadline so I'm going to use Rebass to get it shipped.

**Comment by lachlanjc** [comment]
@MaxWofford That works! 👍

**Comment by lachlanjc** [comment]
@MaxWofford The build is erroring because `window` isn't defined when the site is server-rendering: https://dashboard.heroku.com/apps/lachlan-website/activity/builds/f26f314a-17bf-4ed8-89c0-483383929692

**Pull request merged**
