### PR TITLE
Fix right align, closes #87

### LINKED ISSUE #87: Container text not centered
This was captured from the site's homepage. I think the components are still using the previous DS iteration.

capture

### PR DESCRIPTION
**Pull request by ifvictr**
The right-align was leftover from the older Start component design. This should make it so that it's completely centered.

### CODE REVIEW

**Comment by ifvictr** [comment]
Also, this is issue/PR #100! :100: :tada:

**Comment by lachlanjc** [comment]
Thanks Victor! The bug here is actually the flex direction—on mobile, it should all be centered, but on desktop, the two blocks should go next to each other, so the right text align is correct.

Also, this PR doesn't make any changes 👀

**Comment by ifvictr** [comment]
Didn't I change `text-align` with that?

Before:



After:

**Comment by maxwofford** [comment]
What's the status of this PR @ifvictr?

**Comment by ifvictr** [comment]
@MaxWofford It works.

**Comment by maxwofford** [comment]
This is what the Heroku deploy looks like for me:

screenshot from 2018-01-23 12-36-34

**Comment by lachlanjc** [comment]
This PR doesn’t make any changes, but I’ve fixed the issue (perhaps on Gatsby? I don’t remember)

**Comment by maxwofford** [comment]
Going to go ahead and close this.

**Pull request closed without merging**
