### PR TITLE
Add netlify badge to footer

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by lachlanjc** [comment]
Can we move this into the last column?
Screen Shot 2020-01-04 at 10 18 11 AM

Also, in dark mode: (`dark` prop on Footer)
Screen Shot 2020-01-04 at 10 18 41 AM

**Comment by maxwofford** [comment]
Love these changes. Couldn’t get the site building locally, so I was using netlify builds to see changes

Max Wofford
max@maxwofford.com
Engineering & Operations @ Hack Club ( https://hackclub.com )

**Comment by lachlanjc** [comment]
What's the issue with the local setup? Working as usual for me

**Comment by maxwofford** [comment]
Screen Shot 2020-01-04 at 10 31 11 AM

this happens when I run `ppm run dev` node v13.5.0

**Comment by lachlanjc** [comment]
I'd delete `.cache/`, then `yarn` & try again. If that doesn't work, also delete `public/` & `node_modules/` first.

**Comment by lachlanjc** [comment]
I’m going to close this for now since we’re no longer using Netlify for the site. Feel free to re-open if we still need to do this :+1:

**Pull request closed without merging**
