### PR TITLE
Add alt attributes to bubbles

### PR DESCRIPTION
**Pull request by merelinguist**
All images should have an [alt] attribute: 

https://dequeuniversity.com/rules/axe/2.2/image-alt

### CODE REVIEW

**Comment by zachlatta** [comment]
Hi @merelinguist, thank you for the pull request. I think the purpose of that rule from Deque University is to make sure that images are accessible to screen readers. Adding a blank `alt` attribute doesn't make the bubbles any more accessible to screenreaders since it's just an empty string.

Will let @lachlanjc review this PR and figure out next steps.

**Comment by merelinguist** [comment]
(To the best of my knowledge), it's considered best practice to use null alt text on img elements for images that AT should ignore. If there is no alt attribute at all, screenreaders and the like will read the src instead.

W3: https://www.w3.org/TR/WCAG20-TECHS/H67.html

**Comment by lachlanjc** [comment]
@merelinguist That is correct, empty strings are preferable. Thanks for the PR!

**Comment by zachlatta** [comment]
Ah! I'm sorry about this. I guess this is why @lachlanjc is our main web developer and not me :-).

Learn something new every day.

**Pull request merged**
