### PR TITLE
Add People page

### PR DESCRIPTION
**Pull request by ifvictr**
URL: https://hackclub.com/people

Screenshot:

----

This changes the Team page into a page for all people that have helped Hack Club in some way.

To-do:
- [x] Break up people into categories
- [x] Get processed photos of Matthew and Sean
- [x] Set up https://hackclub.com/team to redirect to https://hackclub.com/people

Idea:
- Use Section to hold categories to allow use of background colors :sparkles:

### CODE REVIEW

**Comment by ifvictr** [comment]
@lachlanjc This is ready to be merged!

**Comment by lachlanjc** [comment]
Any idea why we don't have a Heroku deploy preview here? @MaxWofford

**Comment by maxwofford** [comment]
Not sure why that didn't trigger -- just requested it from Heroku

**Comment by maxwofford** [comment]
@ifvictr the advisory board cards feel kinda sparse. What if you add a quick bio for each?

**Comment by ifvictr** [comment]
@MaxWofford That part still needs to be filled. @zachlatta's going to write a few bios for it.

**Comment by lachlanjc** [comment]
I think this needs a little more polish—I’m going to vote for one color for each of the new sections (keep them on the core team, I think?). And in the next few days I’ll tweak some alignment stuff in the Bios.

**Comment by ifvictr** [comment]
@lachlanjc To clarify, are you talking about one Bio background color per section (e.g., core = red, contributors = blue)?

**Comment by lachlanjc** [comment]
@ifvictr I think so. It might work to keep the varied colors just on the Core section, but let’s pick one (blue, gray, etc) for each of the other sections.

**Comment by ifvictr** [comment]
@lachlanjc Contributors have a blue background, and alumni have red backgrounds now. I think this should be ready to merge now.

**Comment by lachlanjc** [comment]
Thanks @ifvictr. I'm going to get Gatsby up and running and then apply this.

**Comment by lachlanjc** [comment]
Replaced by #126.

**Pull request closed without merging**
