### PR TITLE
worked on santa file

### PR DESCRIPTION
**Pull request by aditya1rawat**
formatted project and added new registration section with link to rules as well

### CODE REVIEW

**Comment by aditya1rawat** [comment]
idk why the deployment looks different compared to when i run it locally

**Comment by sampoder** [comment]
@aditya1rawat could you possibly clean up the PR and remove the 110 files changed to be 1 lol

**Comment by aditya1rawat** [comment]
lmao sure, my bad

**Comment by aditya1rawat** [comment]
ill delete my fork cuz i can't figure out how to revert my commits

**Comment by sampoder** [comment]
~~github desktop~~

**Pull request closed without merging**
