### PR TITLE
fixed santa stuff 😅

### PR DESCRIPTION
**Pull request by aditya1rawat**

### CODE REVIEW

**Comment by aditya1rawat** [comment]
the other 97 are just optimized svgs. they shouldn't change anything within the website

**Comment by aditya1rawat** [comment]
@sampoder fixed

**Review by sampoder — CHANGES_REQUESTED** [review]
Screenshot 2020-12-08 at 9 22 41 PM

Could you look into this? Seems to have been added. Also going to revert the ImgBot commit as it often messes things up :) 

@qmogh could you take a look at the changes?

**Comment by sampoder** [comment]
(the bundling may be the snowing stuff and not this PR causing it, just seems more prevalent here lol)

**Comment by aditya1rawat** [comment]
> Screenshot 2020-12-08 at 9 22 41 PM
> 
> Could you look into this? Seems to have been added. Also going to revert the ImgBot commit as it often messes things up :)

Yeah reverting the ImgBot is fine, but I don't know why the deployed version screws up the snow because it worked perfectly when I was running the localhost server

**Comment by sampoder** [comment]
I swear @ImgBotApp why are you back

**Comment by aditya1rawat** [comment]
wait i didn't even merge that pr lmao. 🤔

**Comment by aditya1rawat** [comment]
might be automated. ill fix that

**Comment by sampoder** [comment]
Closing because time has passed, thanks @aditya1rawat though!

**Comment by aditya1rawat** [comment]
yeah np. i think it was just the snow library issue. it's all good tho

**Pull request closed without merging**
