### PR TITLE
Added leo

### PR DESCRIPTION
**Pull request by leomcelroy**

### CODE REVIEW

**Review by sampoder — APPROVED** [review]

**Comment by sampoder** [comment]
hiiiii Leo!

**Comment by sampoder** [comment]
(I hope its alright I merged this)

**Comment by leomcelroy** [comment]
The plan was to merge it. I think Max was maybe going to look at it first but props for taking initiative.

**Comment by sampoder** [comment]
ah, sorry for jumping the gun Max

**Pull request merged**
