### PR TITLE
Kill swkiller

### PR DESCRIPTION
**Pull request by lachlanjc**
@maxwofford—noticed we still have this. It's been like 1.5 years since we did this. Can probably remove it now? I'll let you make that call since I don't have the context here.

### CODE REVIEW

**Comment by maxwofford** [comment]
the intent of the killer is to stick around indefinitely & fix clients that were afflicted with the broken cache bug. that bug is long gone for my own use of hackclub.com, but I can totally imagine people out there who viewed our site 1.5 years ago and are returning for the first time now (esp w/ things like the articles being published).

I don't know if chrome now has an expiration date for service workers, but that'd be the ideal time to remove this. from what I was reading about while fixing this, the buggy service workers won't expire without outside intervention.

**Comment by maxwofford** [comment]
if you've got any ideas for how to do this without this file sitting here though, I'm all down for it. kinda sucks to have artifacts like this lying around

**Comment by lachlanjc** [comment]
Ok, that makes sense, yeah. Definitely a tiny percentage of users but at the same time I guess we have no ability to fix it for them otherwise. Good call

**Comment by lachlanjc** [comment]
@maxwofford I just discovered the service worker killer doesn't actually load. In the HTML:

```html
<script data-react-helmet="true">[object Object]; serviceWorkerKiller()</script>
```

Sooo it hasn't actually been doing anything, & causes a syntax error on every page.

**Comment by maxwofford** [comment]
Screenshot 2020-01-07 20 38 06

just loaded the page & saw it console.log that it's running ("no service workers found"). Think that loading in the main page through __dangerouslySetInnerHTML is incorrect though.

**Comment by maxwofford** [comment]
Also just registered a service worker in the console & it was removed correctly on reload, so the script is definitely running. Not entirely sure how though.

**Comment by lachlanjc** [comment]
We live in a surreal reality, Max.

**Pull request closed without merging**
