### PR TITLE
Kill Challenges

### PR DESCRIPTION
**Pull request by lachlanjc**
Screen Shot 2019-12-23 at 1 25 39 AM

I think the time has come…we decided awhile back we were never running another Challenge with the current game architecture, so may as well pull the plug?

I rejiggered the Footer for changing the link layout as well, to end its 4-column state.

@polytroper @maxwofford I'll let one of you make the final call here

### CODE REVIEW

**Comment by maxwofford** [comment]
Love this, but sad to see previous submissions disappear. Maybe there's a tasteful way to show "previous challenge submissions"? Either a random rotation or a list of personal favorites– would love to see those "art challenge" projects still be shown off.

**Comment by maxwofford** [comment]
just looked at the build preview, this is great (also great how decluttered the footer is). merging!

**Comment by lachlanjc** [comment]
Yeah, it’s true, though we were only showing one challenge’s submissions anyway. Wouldn’t be tough to make read-only archival pages with all submissions, though.

**Comment by maxwofford** [comment]
Yeah, don't image the challenge context matters too much anymore anyways (ie. having an art submission next to a cli submission)

**Comment by lachlanjc** [comment]
Is this important enough I should throw together a site to show submissions? I feel like no one would look at it but it's very easy technically.

**Comment by maxwofford** [comment]
Without expecting to run a future challenge, i'd also be fine with hardcoding them into this page

**Comment by maxwofford** [comment]
to clarify, use-case is me telling someone "we've run community challenges in the past, check out what people built" and handing them a link

**Pull request merged**
